bash run_kubernetes.sh
Authenticating with existing credentials...
Login Succeeded
Error from server (AlreadyExists): pods "priceprediction" already exists
NAME              READY   STATUS    RESTARTS   AGE
priceprediction   1/1     Running   1          17m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 444-468-346
[2020-05-14 16:04:32,991] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2020-05-14 16:04:33,003] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-05-14 16:04:33,012] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-05-14 16:04:33,014] INFO in app: line 18 scaler :
StandardScaler(copy=True, with_mean=True, with_std=True)
[2020-05-14 16:04:33,015] INFO in app: line 20 scaled_adhoc_predict:
[[0. 0. 0. 0. 0. 0.]]
[2020-05-14 16:04:33,015] INFO in app: line 65 scaled_payload:
[[0. 0. 0. 0. 0. 0.]]
[2020-05-14 16:04:33,016] INFO in app: line 69 Prediction value: [20.35373177134412]

127.0.0.1 - - [14/May/2020 16:04:33] "POST /predict HTTP/1.1" 200 -
